portal/Models/Region.cs
namespace TDMS.Portal.Models
{
  public class Region
  {
    public string RegionId { get; set; } = "";
    public string RegionName { get; set; } = "";
    public int RegionNumber { get; set; } = 0;
  }
}

portal/Controllers/RegionController.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;

using TDMS.Portal.Models;
using TDMS.Portal.Extensions.Alerts;
using TDMS.Portal.Contexts;

namespace TDMS.Portal.Controllers
{
  public class RegionController : Controller
  {
    public IActionResult Index()
    {
      return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Index(Region reg, string cmd)
    {
      string result = "Invalid command type";
      if (ModelState.IsValid)
      {
        if (cmd == "Delete")
          result = RegionContext.Delete(reg);

        else
          result = RegionContext.Save(reg);
      }

      if (result == "")
        return RedirectToAction("Index").WithSuccess("Success", (cmd == "Delete" ? "Deleting" : "Saving") + 
          " region with id [" + reg.RegionId + "]");

      else
        return View(reg).WithDanger("Error", result);
    }

    public IActionResult Modify(string id)
    {
      string ID = string.IsNullOrEmpty(id) ? "" : id;
      Region reg = RegionContext.GetItem(ID) ?? new Region();

      return View(reg);
    }

    public IActionResult GetData(int limit = 10, int offset = 0, string search = "")
    {
      if (Helper.getRole(HttpContext.Session.GetInt32("user_role")) == Models.User.RoleEnum.Administrator)
      {
        int totalData = RegionContext.ItemsCount(search);
        if (totalData > 0)
          return Ok(new Table
          {
            total = totalData,
            rows = RegionContext.GetItems(limit, Helper.OffsetToPage(limit, offset), search)
          });

        return Ok(new Table { rows = new List<string>() });
      }

      return RedirectToAction("Index", "Login");
    }
  }
}

portal/Views/Region/Index.cshtml
@{
  if (getRole(Context.Session.GetInt32("user_role")) != TDMS.Portal.Models.User.RoleEnum.Administrator)
  {
    Context.Response.Redirect("/Home");
  }
}

<!-- Page Heading -->
<div class="d-flex flex-row mb-4">
  <h1 class="h3 mb-0 text-gray-800">Region List</h1>
</div>

<div id="toolbar">
  <a href="/Region/Modify" class="btn btn-primary btn-icon-split">
    <span class="icon text-white-50"><em class="fas fa-pencil-alt"></em></span>
    <span class="text">Add</span>
  </a>
</div>

<div class="card mb-4">
  <div class="card-body">
    <table id="dtTable" data-toggle="table" data-thead-classes="bg-info text-white"
           data-pagination="true" data-search="true" data-side-pagination="server" 
           data-url='@Url.Action("GetData","Region")' data-defer-url='@Url.Action("GetData","Region")'
           data-toolbar="#toolbar">
      <thead>
        <tr>
          <th data-formatter="IndexFormatter">No.</th>
          <th data-field="regionId">Region Id</th>
          <th data-field="regionNumber">Number</th>
          <th data-field="regionName">Name</th>
          <th data-formatter="actionFormat" data-align="center"></th>
        </tr>
      </thead>
    </table>
  </div>
</div>

@section Scripts {
  <script>
    function actionFormat(value, row) {
      return '<a href="/Region/Modify/' + row.regionId + '" title="Modify" class="btn btn-success btn-circle btn-sm">' +
        '<i class="fa fa-edit"></i></a>';
    }

    $(document).ready(function () {
      $("#liRegion").addClass("active");
    });
  </script>
}

portal/Views/Region/Modify.cshtml
@model TDMS.Portal.Models.Region
@{
  if (getRole(Context.Session.GetInt32("user_role")) != TDMS.Portal.Models.User.RoleEnum.Administrator)
  {
    Context.Response.Redirect("/Home");
  }
  var isUpdate = !string.IsNullOrEmpty(Model.RegionName);
}
<!-- Page Heading -->
<div class="d-flex flex-row mb-4">
  <h1 class="h3 mb-0 text-gray-800">Region Forms</h1>
</div>

@using (Html.BeginForm("Index", "Region", FormMethod.Post))
{
  @Html.AntiForgeryToken()
  @Html.ValidationSummary(true)

  <!-- Content Row -->
  <div class="card">
    <div class="card-body">
      <div class="form-group row">
        <label for="Id" class="col-sm-2 col-form-label">Id : </label>
        @Html.TextBoxFor(m => m.RegionId, getAttrs(isUpdate, true, FormControlCol))
      </div>

      <div class="form-group row">
        <label for="Name" class="col-sm-2 col-form-label">Name : </label>
        @Html.TextBoxFor(m => m.RegionName, getAttrs(false, true, FormControlCol))
      </div>

      <div class="form-group row">
        <label for="Number" class="col-sm-2 col-form-label">Number : </label>
        @Html.TextBoxFor(m => m.RegionNumber, getAttrs(false, true, FormControlNumberCol))
      </div>
    </div>

    <div class="card-footer">
      <button name="cmd" value="@(isUpdate ? "Update" : "Insert")" class="@FormControlButtonSuccess">
        <span class="icon text-white-50"><em class="fas fa-save"></em></span>
        <span class="text">Save</span>
      </button>
      <button name="cmd" value="Delete" class="@FormControlButtonDanger" @(isUpdate ? "" : "disabled")>
        <span class="icon text-white-50"><em class="fas fa-cut"></em></span>
        <span class="text">Delete</span>
      </button>
      <a href="/Region" class="@FormControlButtonDark">
        <span class="icon text-white-50"><em class="fas fa-times"></em></span>
        <span class="text">Cancel</span>
      </a>
    </div>
  </div>
}

@section Scripts {
  <script>
    $(document).ready(function () {
      $("#liRegion").addClass("active");
    });
  </script>
}